{
 "title": "IoKey",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "DTSelection",
    "label": "Data Logger",
    "query": "SELECT \"datalogger\" FROM \"mqtt_consumer\" GROUP BY \"datalogger\""
   }
  ]
 },
 "panels": [
  {
   "title": "Data Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Temperature S1 (°C)",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"temperature_temperature_s1\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "temperature_temperature_s1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=~", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Humidity S1 (%)",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"humidity_humidity_s1\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "humidity_humidity_s1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Temperature S2 (°C)",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"temperature_temperature_s2\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "temperature_temperature_s2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Humidity S2 (%)",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"humidity_humidity_s2\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "humidity_humidity_s2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Temperature S3 (°C)",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"temperature_temperature_s3\" FROM \"mqtt_consumer\" WHERE (\"datalogger\"= $DTSelection) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "temperature_temperature_s3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Humidity S3 (%)",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"humidity_humidity_s3\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "humidity_humidity_s3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Battery (%)",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"battery_level\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=", "value": "/^$DTSelection$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Sensor1",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"temperature_temperature_s1\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature_temperature_s1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=~", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Sensor2",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"temperature_temperature_s2\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature_temperature_s2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=~", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Sensor3",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"temperature_temperature_s3\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature_temperature_s3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=~", "value": "/^$DTSelection$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Sensor1",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"humidity_humidity_s1\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter",
     "select": [
      [
       { "params": [ "humidity_humidity_s1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=~", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Sensor2",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"humidity_humidity_s2\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter",
     "select": [
      [
       { "params": [ "humidity_humidity_s2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=~", "value": "/^$DTSelection$/" }
     ]
    },
    {
     "alias": "Sensor3",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"humidity_humidity_s3\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" =  $DTSelection) AND $timeFilter",
     "select": [
      [
       { "params": [ "humidity_humidity_s3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=~", "value": "/^$DTSelection$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "description": "Remaining battery level",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT \"battery_level\" FROM \"mqtt_consumer\" WHERE (\"datalogger\" = $DTSelection) AND $timeFilter",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "datalogger::field", "operator": "=", "value": "/^$DTSelection$/" }
     ]
    }
   ]
  }
 ]
}